# Generated by Django 5.2.8 on 2025-12-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id_partidopolitico', models.AutoField(primary_key=True, serialize=False)),
                ('lider', models.CharField(blank=True, max_length=150, null=True)),
                ('candidato', models.CharField(blank=True, max_length=150, null=True)),
                ('anio_fundacion', models.IntegerField(blank=True, null=True)),
                ('pill_color', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('vector_ideologico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partidospoliticos',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('enunciadopregunta', models.TextField()),
                ('peso_impacto', models.FloatField()),
                ('vector_influencia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'preguntas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
