# Generated by Django 5.2.9 on 2026-01-08 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidopolitico',
            old_name='candidato',
            new_name='lider_candidato',
        ),
        migrations.RenameField(
            model_name='partidopolitico',
            old_name='lider',
            new_name='nombre_partido',
        ),
        migrations.AddField(
            model_name='partidopolitico',
            name='descripcion_corta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partidopolitico',
            name='espectro_politico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partidopolitico',
            name='estado_inscripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partidopolitico',
            name='propuestas_clave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partidopolitico',
            name='sentencias_polemicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='ambito_general',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='flag_cuestionario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tema_especifico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HistorialMatch',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('similitud_pct', models.FloatField(blank=True, null=True)),
                ('fk_id_partidopolitico', models.ForeignKey(db_column='fk_id_partidopolitico', on_delete=django.db.models.deletion.CASCADE, to='api_quiz.partidopolitico')),
                ('fk_id_usuario', models.ForeignKey(db_column='fk_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='api_quiz.usuario')),
            ],
            options={
                'db_table': 'historial_match',
                'unique_together': {('fk_id_usuario', 'fk_id_partidopolitico')},
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('valor_seleccionado', models.IntegerField(blank=True, null=True)),
                ('vector_resultante', models.TextField(blank=True, null=True)),
                ('fk_id_partidopolitico', models.ForeignKey(blank=True, db_column='fk_id_partidopolitico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_quiz.partidopolitico')),
                ('fk_id_pregunta', models.ForeignKey(db_column='fk_id_pregunta', on_delete=django.db.models.deletion.CASCADE, to='api_quiz.pregunta')),
                ('fk_id_usuario', models.ForeignKey(db_column='fk_id_usuario', on_delete=django.db.models.deletion.CASCADE, to='api_quiz.usuario')),
            ],
            options={
                'db_table': 'respuestas',
                'unique_together': {('fk_id_usuario', 'fk_id_pregunta')},
            },
        ),
    ]
