# Generated by Django 5.2.9 on 2026-01-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quiz', '0002_rename_candidato_partidopolitico_lider_candidato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partidopolitico',
            old_name='lider_candidato',
            new_name='candidato',
        ),
        migrations.RenameField(
            model_name='partidopolitico',
            old_name='sentencias_polemicas',
            new_name='historia_breve',
        ),
        migrations.RenameField(
            model_name='partidopolitico',
            old_name='nombre_partido',
            new_name='lider',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='ambito_general',
            new_name='subcategoria',
        ),
        migrations.RenameField(
            model_name='pregunta',
            old_name='tema_especifico',
            new_name='temacategoria',
        ),
        migrations.RemoveField(
            model_name='partidopolitico',
            name='espectro_politico',
        ),
        migrations.RemoveField(
            model_name='partidopolitico',
            name='estado_inscripcion',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='flag_cuestionario',
        ),
        migrations.AddField(
            model_name='partidopolitico',
            name='financiamiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partidopolitico',
            name='representacion_actual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partidopolitico',
            name='sentencias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
